### PR TITLE
#163253387- improvement of ui based on lfa feedback

### PR DESCRIPTION
**Pull request by openwell**
### What does this PR do?
- This PR improves the UI landing page and other areas
### How should this be manually tested?
- Pull this branch **ch-implementation-feedback-lfa-163253387** off this repository
- Navigate to index.html to access the app
### Any background context you want to provide?
None
### What are the relevant pivotal tracker stories?
[163253387](https://www.pivotaltracker.com/story/show/163253387)
### Screenshots (if appropriate)
None
### Questions
None

### CODE REVIEW

**Comment by megame24** [comment]
The title and description of this PR don't match the files changed. You mainly worked on the front-end html/css/js but the PR refers to the API. Was that the intended outcome?

**Comment by openwell** [comment]
This PR is a wrong pull request, this pull request is for the UI feedback you gave me. 
I must have closed it and did a new Pull Request, taking it for the other API PR.  based on the fact that the name is slightly similar to that of the logic feedback PR.

So it looks like the API PR i closed will be returned back to, so has to find solution to the issue.

**Comment by megame24** [comment]
> This PR is a wrong pull request, this pull request is for the UI feedback you gave me.
> I must have closed it and did a new Pull Request, taking it for the other API PR. based on the fact that the name is slightly similar to that of the logic feedback PR.
> 
> So it looks like the API PR i closed will be returned back to, so has to find solution to the issue.

Then update the PR description and name to match the PR.

**Comment by megame24** [comment]
Provide a description for PR.

**Comment by openwell** [comment]
Based on the last comment, the PR was a wrong PR (meaning I have merged the PR before, then I closed it mistaking and reopened it as my API PR, taking it for the API PR I had an issue with), due to the pressure of trying to meet up with Friday review.  I was meant to close it again but due to our last meeting, I left it open. hoping by Monday you will give me the go-ahead to do so. 
because the PR is meant for gh-pages (if it was to be merged) and not develop. 
Am working on git re-base to try to fix the other PR. either way, I will add the details as requested

**Comment by megame24** [comment]
> Based on the last comment, the PR was a wrong PR (meaning I have merged the PR before, then I closed it mistaking and reopened it as my API PR, taking it for the API PR I had an issue with), due to the pressure of trying to meet up with Friday review. I was meant to close it again but due to our last meeting, I left it open. hoping by Monday you will give me the go-ahead to do so.
> because the PR is meant for gh-pages (if it was to be merged) and not develop.
> Am working on git re-base to try to fix the other PR. either way, I will add the details as requested

To get you correctly, this PR has been merged, and you'll like to close it?

**Comment by openwell** [comment]
Yes, This it has been merged it was my 21th PR according to the logs (https://github.com/openwell/questioner/pull/21) and I made the mistake of doing a PR on it again, due to the similarity of the name with the API feedback.

**Comment by megame24** [comment]
Ok, you can close the PR

**Pull request closed without merging**
